blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://registry.terraform.io/providers/batonogov/threexui/latest/docs
    about: Check the documentation before filing an issue
