// Package main implements github-cache: a local MITM forward proxy that makes
// 3x-ui's xray-version acceptance tests fully offline and deterministic.
//
// Background (issue #285): three acceptance tests rely on the panel reaching
// GitHub at runtime — GetXrayVersions (api.github.com) and InstallXray
// downloads (github.com). Those URLs are hardcoded in 3x-ui as HTTPS, and the
// panel's outbound HTTP client honors HTTPS_PROXY when panel_outbound is unset
// (see internal/util/netproxy/netproxy.go: an empty proxyURL yields a plain
// *http.Client whose transport is http.DefaultTransport, i.e. ProxyFromEnvironment).
// Routing the panel through this proxy therefore needs no upstream or provider
// changes.
//
// Because the targets are HTTPS, Go's forward-proxy support issues a CONNECT
// and then runs TLS end-to-end over the tunnel. A plain file-serving proxy
// cannot see the request without terminating TLS, so this proxy performs a
// MITM: it presents a leaf certificate for api.github.com / github.com signed
// by a CA generated at startup, which the 3x-ui container trusts via
// SSL_CERT_FILE (see docker-compose.yaml). Over that TLS session it serves
// vendored fixtures from disk. CONNECT to any other host is transparently
// tunnelled (passthrough) so the panel's unrelated outbound traffic — public
// IP detection and the like — keeps working unchanged. The cache is therefore
// invisible to everything except the two GitHub hosts, which keeps the change
// surgical: the xray-version tests have zero outbound network, while every
// other panel feature behaves exactly as before.
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// githubHosts are the only CONNECT targets this proxy will MITM. They match
// the hardcoded URLs in 3x-ui's internal/web/service/server.go:
//
//	XrayURL = "https://api.github.com/repos/XTLS/Xray-core/releases"
//	url     = "https://github.com/XTLS/Xray-core/releases/download/<v>/Xray-linux-64.zip"
var githubHosts = map[string]struct{}{
	"api.github.com": {},
	"github.com":     {},
}

func main() {
	addr := flag.String("addr", ":3128", "listen address")
	fixtures := flag.String("fixtures", "/app/fixtures", "path to the vendored fixture tree")
	caCert := flag.String("ca-cert", "/ca/ca.crt", "CA certificate (PEM) generated by the entrypoint")
	caKey := flag.String("ca-key", "/ca/ca.key", "CA private key (PEM) generated by the entrypoint")
	flag.Parse()

	caCertObj, caKeyObj, err := loadCA(*caCert, *caKey)
	if err != nil {
		log.Fatalf("load CA: %s (the entrypoint must generate %s/%s before starting)", err, *caCert, *caKey)
	}

	proxy := &proxy{
		fixtures: *fixtures,
		leaves: &leafCache{
			cache:  make(map[string]tls.Certificate),
			caCert: caCertObj,
			caKey:  caKeyObj,
		},
	}

	srv := &http.Server{
		Addr:              *addr,
		Handler:           proxy,
		ReadHeaderTimeout: 10 * time.Second,
	}
	log.Printf("github-cache listening on %s, serving fixtures from %s", *addr, *fixtures)
	if err := srv.ListenAndServe(); err != nil {
		log.Fatalf("server: %s", err)
	}
}

type proxy struct {
	fixtures string
	leaves   *leafCache
}

func (p *proxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// /healthz is the readiness probe used by docker-compose healthcheck and
	// the depends_on gate. It is served over plain HTTP, no CONNECT.
	if r.Method == http.MethodGet && r.URL.Path == "/healthz" {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
		return
	}

	if r.Method == http.MethodConnect {
		p.handleConnect(w, r)
		return
	}

	// A plain (non-CONNECT) request means some client is trying to use us as
	// an HTTP (not HTTPS) forward proxy. The panel makes no such requests in
	// the acceptance tests, so fail loud.
	host := r.Host
	if host == "" {
		host = r.URL.Host
	}
	log.Printf("refused non-CONNECT %s %s (only HTTPS via CONNECT is proxied)", r.Method, host)
	http.Error(w, "github-cache only proxies HTTPS via CONNECT", http.StatusForbidden)
}

func (p *proxy) handleConnect(w http.ResponseWriter, r *http.Request) {
	hostPort := r.Host
	if hostPort == "" {
		hostPort = r.URL.Host
	}
	host, _, err := net.SplitHostPort(hostPort)
	if err != nil {
		host = hostPort
	}

	if _, ok := githubHosts[host]; !ok {
		// The panel legitimately reaches non-GitHub hosts too (its own public-IP
		// detection probes ident.me / ipify / icanhazip / …). Those calls are
		// unrelated to the xray-version tests, so rather than refuse them (which
		// would break the panel's IP detection and spray timeouts into its
		// status responses), we transparently tunnel the CONNECT to the real
		// target. The cache is therefore invisible to every outbound host except
		// api.github.com and github.com, which keeps the change surgical and
		// preserves the panel's pre-cache behaviour for everything else.
		p.tunnel(w, hostPort)
		return
	}

	hj, ok := w.(http.Hijacker)
	if !ok {
		http.Error(w, "hijack unsupported", http.StatusInternalServerError)
		return
	}
	client, _, err := hj.Hijack()
	if err != nil {
		log.Printf("hijack %s: %s", host, err)
		return
	}
	// Tell the client the tunnel is up. We then take over as the TLS server.
	if _, err := client.Write([]byte("HTTP/1.1 200 Connection Established\r\n\r\n")); err != nil {
		log.Printf("write CONNECT ack %s: %s", host, err)
		_ = client.Close()
		return
	}

	leaf, err := p.leaves.get(host)
	if err != nil {
		log.Printf("leaf cert for %s: %s", host, err)
		_ = client.Close()
		return
	}

	tlsConn := tls.Server(client, &tls.Config{
		Certificates: []tls.Certificate{leaf},
		// Advertise only HTTP/1.1 so the client does not negotiate h2 (which
		// this single-conn server does not implement). The panel's Go client
		// happily falls back to HTTP/1.1.
		NextProtos: []string{"http/1.1"},
		MinVersion: tls.VersionTLS12,
	})
	if err := tlsConn.Handshake(); err != nil {
		log.Printf("TLS handshake %s: %s", host, err)
		_ = tlsConn.Close()
		return
	}

	// Serve HTTP/1.1 over the single hijacked TLS connection. The inner
	// handler dispatches to fixtures based on Host + path.
	srv := &http.Server{
		Handler:           http.HandlerFunc(p.serveFixture),
		ReadHeaderTimeout: 30 * time.Second,
	}
	_ = srv.Serve(&singleConnListener{conn: tlsConn})
}

// tunnel is a plain TCP forward for CONNECT targets we do not MITM (anything
// other than api.github.com / github.com). It is a transparent pipe: bytes in
// either direction are copied until one side closes. This keeps the panel's
// non-GitHub outbound traffic (public-IP detection, etc.) working unchanged.
func (p *proxy) tunnel(w http.ResponseWriter, target string) {
	hj, ok := w.(http.Hijacker)
	if !ok {
		http.Error(w, "hijack unsupported", http.StatusInternalServerError)
		return
	}
	client, _, err := hj.Hijack()
	if err != nil {
		log.Printf("tunnel hijack %s: %s", target, err)
		return
	}

	dst, err := net.DialTimeout("tcp", target, 30*time.Second)
	if err != nil {
		log.Printf("tunnel dial %s: %s", target, err)
		_, _ = client.Write([]byte("HTTP/1.1 502 Bad Gateway\r\n\r\n"))
		_ = client.Close()
		return
	}

	if _, err := client.Write([]byte("HTTP/1.1 200 Connection Established\r\n\r\n")); err != nil {
		log.Printf("tunnel ack %s: %s", target, err)
		_ = client.Close()
		_ = dst.Close()
		return
	}

	log.Printf("tunnel %s (passthrough)", target)
	// Bidirectional copy. Close both conns when either direction finishes so
	// the two goroutines below always unblock.
	done := make(chan struct{}, 2)
	cp := func(dst, src net.Conn) {
		_, _ = io.Copy(dst, src)
		done <- struct{}{}
	}
	go cp(dst, client)
	go cp(client, dst)
	<-done
	_ = client.Close()
	_ = dst.Close()
	<-done
}

// serveFixture maps the inner (decrypted) request to a vendored fixture file.
func (p *proxy) serveFixture(w http.ResponseWriter, r *http.Request) {
	abs, contentType, ok := fixtureFor(p.fixtures, r.Host, r.URL.Path)
	if !ok {
		log.Printf("404 %s%s (no fixture; query=%q)", r.Host, r.URL.Path, r.URL.RawQuery)
		http.NotFound(w, r)
		return
	}

	f, err := os.Open(abs)
	if err != nil {
		log.Printf("open %s: %s", abs, err)
		http.Error(w, "fixture unavailable", http.StatusInternalServerError)
		return
	}
	defer f.Close()

	w.Header().Set("Content-Type", contentType)
	log.Printf("200 %s %s%s → %s", r.Method, r.Host, r.URL.Path, filepath.Base(abs))
	http.ServeContent(w, r, filepath.Base(abs), time.Time{}, f)
}

// fixtureFor resolves a (host, path) pair to a fixture file and its content
// type. Returns ok=false when there is no matching fixture, which the caller
// turns into a 404 (fail loud). Extracted for unit testing.
func fixtureFor(root, host, urlPath string) (abs, contentType string, ok bool) {
	switch {
	case host == "api.github.com" && strings.HasPrefix(urlPath, "/repos/XTLS/Xray-core/releases"):
		// 3x-ui hits https://api.github.com/repos/XTLS/Xray-core/releases
		// (optionally with a ?per_page= query, which we ignore). The panel
		// only reads tag_name from the returned array.
		return filepath.Join(root, "api.github.com", "repos", "XTLS", "Xray-core", "releases.json"),
			"application/json; charset=utf-8", true

	case host == "github.com" && strings.HasPrefix(urlPath, "/XTLS/Xray-core/releases/download/"):
		// 3x-ui downloads https://github.com/XTLS/Xray-core/releases/download/<v>/Xray-linux-64.zip
		// Mirror the path verbatim under the fixture root so adding a version
		// is just "drop the zip in place".
		rel := strings.TrimPrefix(urlPath, "/")
		candidate := filepath.Join(root, "github.com", rel)
		return candidate, "application/zip", true

	default:
		return "", "", false
	}
}

// singleConnListener yields exactly one connection, then returns errClosed on
// the next Accept so http.Server.Serve returns and the per-CONNECT goroutine
// exits. Keep-alive within the single connection still works because Serve
// reads multiple requests from the one connection until it closes.
type singleConnListener struct {
	conn net.Conn
	done bool
}

var errListenerClosed = errors.New("singleConnListener: closed")

func (l *singleConnListener) Accept() (net.Conn, error) {
	if !l.done {
		l.done = true
		return l.conn, nil
	}
	return nil, errListenerClosed
}

func (l *singleConnListener) Close() error   { return nil }
func (l *singleConnListener) Addr() net.Addr { return &net.TCPAddr{} }

// --- CA + leaf certificate machinery ---------------------------------------

func loadCA(certPath, keyPath string) (*x509.Certificate, *rsa.PrivateKey, error) {
	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		return nil, nil, err
	}
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return nil, nil, errors.New("no PEM block in CA cert")
	}
	caCert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parse CA cert: %w", err)
	}

	keyPEM, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, nil, err
	}
	keyBlock, _ := pem.Decode(keyPEM)
	if keyBlock == nil {
		return nil, nil, errors.New("no PEM block in CA key")
	}
	// openssl genrsa emits PKCS#1; openssl genpkey emits PKCS#8. Accept both
	// so the entrypoint can use either.
	if caKey, err := x509.ParsePKCS1PrivateKey(keyBlock.Bytes); err == nil {
		return caCert, caKey, nil
	}
	if anyKey, err := x509.ParsePKCS8PrivateKey(keyBlock.Bytes); err == nil {
		if rsaKey, ok := anyKey.(*rsa.PrivateKey); ok {
			return caCert, rsaKey, nil
		}
		return nil, nil, errors.New("CA key is not RSA")
	}
	return nil, nil, errors.New("unrecognised CA private key format (want PKCS#1 or PKCS#8 RSA)")
}

type leafCache struct {
	mu     sync.RWMutex
	cache  map[string]tls.Certificate
	caCert *x509.Certificate
	caKey  *rsa.PrivateKey
}

func (c *leafCache) get(host string) (tls.Certificate, error) {
	c.mu.RLock()
	leaf, ok := c.cache[host]
	c.mu.RUnlock()
	if ok {
		return leaf, nil
	}

	c.mu.Lock()
	defer c.mu.Unlock()
	// Double-check after acquiring the write lock.
	if leaf, ok := c.cache[host]; ok {
		return leaf, nil
	}
	leaf, err := c.sign(host)
	if err != nil {
		return tls.Certificate{}, err
	}
	c.cache[host] = leaf
	return leaf, nil
}

func (c *leafCache) sign(host string) (tls.Certificate, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return tls.Certificate{}, err
	}
	tmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: host, Organization: []string{"github-cache"}},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(365 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{host},
		// BasicConstraintsValid omitted on purpose: this is a leaf.
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, c.caCert, &key.PublicKey, c.caKey)
	if err != nil {
		return tls.Certificate{}, err
	}
	return tls.Certificate{
		Certificate: [][]byte{der, c.caCert.Raw},
		PrivateKey:  key,
		Leaf:        mustParseLeaf(der),
	}, nil
}

func mustParseLeaf(der []byte) *x509.Certificate {
	c, err := x509.ParseCertificate(der)
	if err != nil {
		// Should be impossible — we just created it.
		panic(err)
	}
	return c
}

func randomSerial() *big.Int {
	// Upper bound keeps the serial positive and within RFC 5280's 20 octets.
	n, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return big.NewInt(1)
	}
	return n
}
